name: Frontend Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  IMAGE_NAME: savetheplate-frontend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container image
        run: docker build --build-arg ENVIRONMENT=production -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) .
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          passphrase: ''
          envs: IMAGE_NAME,GITHUB_SHA
          script: |
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            # Stop running container
            docker stop $IMAGE_NAME 2> /dev/null || true
            # Remove old container
            docker rm $IMAGE_NAME 2> /dev/null || true
            # Run new container
            docker run -d \
              -p 3000:3000 \
              --restart unless-stopped \
              --name $IMAGE_NAME \
              ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)
