
name: ðŸ¥šðŸŒž DEPLOY DEV
on:
  push:
    branches:
      - dev
  workflow_dispatch:
env:
  REGISTRY: registry.digitalocean.com/cc-dev-registry
  IMAGE_NAME: leftover-frontend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: ðŸ—ï¸ Build and Push
    steps:
      - name: ðŸ§ª Checkout the repo
        uses: actions/checkout@v2
      - name: ðŸ—ï¸ Build container image
        run: docker build --build-arg ENVIRONMENT=staging -t $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) .
      - name: ðŸ“¥ Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: ðŸ”’ Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: ðŸš€ Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: ðŸš¢ Deploy
    steps:
      - name: ðŸš¢ Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 164.90.233.11
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          passphrase: ''
          envs: IMAGE_NAME,REGISTRY,DIGITALOCEAN_ACCESS_TOKEN,GITHUB_SHA
          script: |
            # Login to registry
            docker login -u $DIGITALOCEAN_ACCESS_TOKEN -p $DIGITALOCEAN_ACCESS_TOKEN registry.digitalocean.com
            # Stop running container
            docker stop $IMAGE_NAME 2> /dev/null || true
            # Remove old container
            docker rm $IMAGE_NAME 2> /dev/null || true
            # Run a new container from a new image
            docker run -d \
              -p 3151:3000 \
              --restart on-failure:5 \
              --name $IMAGE_NAME \
              $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)

  